"""Write requirements-kaggle.txt from uv.lock (decision 23).

Kaggle keeps its preinstalled torch and numpy (and the pandas, pyarrow and scipy
built against it). Only the Hugging Face packages the model path depends on are
pinned to the exact versions in uv.lock: transformers, tokenizers (it decides the
token ids), peft, datasets, accelerate, huggingface-hub and safetensors. No
transitive pins. Versions come from `uv export --frozen`, so the file always
matches the lock; tests/test_kaggle.py fails if it drifts.

    uv run python scripts/export_kaggle_requirements.py   (or: make kaggle-requirements)
"""

from __future__ import annotations

import re
import subprocess
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "requirements-kaggle.txt"
PINNED = ("transformers", "tokenizers", "peft", "datasets", "accelerate", "huggingface-hub", "safetensors")


def wanted_packages() -> set[str]:
    """The pinned packages; each must be in uv.lock."""
    locked = {p["name"] for p in tomllib.loads((REPO / "uv.lock").read_text())["package"]}
    missing = set(PINNED) - locked
    if missing:
        raise RuntimeError(f"not in uv.lock: {sorted(missing)}")
    return set(PINNED)


def render() -> str:
    exported = subprocess.run(
        ["uv", "export", "--frozen", "--no-hashes", "--no-emit-project", "--no-header", "--no-dev"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    wanted = wanted_packages()
    lines = [line for line in exported.splitlines() if (m := re.match(r"^([A-Za-z0-9_.-]+)==", line)) and m.group(1).lower() in wanted]
    found = {re.match(r"^([A-Za-z0-9_.-]+)==", line).group(1).lower() for line in lines}
    if found != wanted:
        raise RuntimeError(f"uv export is missing {sorted(wanted - found)}")
    header = [
        "# Generated by scripts/export_kaggle_requirements.py from uv.lock; do not edit.",
        "# Kaggle keeps its preinstalled torch and numpy (decision 23); install jevmark itself with --no-deps.",
    ]
    return "\n".join(header + sorted(lines, key=str.lower)) + "\n"


def main() -> int:
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
