"""Write requirements-kaggle.txt from uv.lock (decision 23).

Kaggle keeps its preinstalled torch; everything else the model path depends on is
pinned to the exact version in uv.lock: transformers, peft, datasets, accelerate,
peft's direct dependencies, and tokenizers (it decides the token ids). torch is
never written. Versions and environment markers come from `uv export --frozen`,
so the file always matches the lock; tests/test_evaluate.py fails if it drifts.

    uv run python scripts/export_kaggle_requirements.py   (or: make kaggle-requirements)
"""

from __future__ import annotations

import re
import subprocess
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "requirements-kaggle.txt"
TOP_LEVEL = ("transformers", "peft", "datasets", "accelerate", "tokenizers")
EXCLUDED = {"torch"}


def wanted_packages() -> set[str]:
    """TOP_LEVEL plus peft's direct dependencies from uv.lock, minus torch."""
    lock = tomllib.loads((REPO / "uv.lock").read_text())
    peft = next(p for p in lock["package"] if p["name"] == "peft")
    return (set(TOP_LEVEL) | {d["name"] for d in peft.get("dependencies", [])}) - EXCLUDED


def render() -> str:
    exported = subprocess.run(
        ["uv", "export", "--frozen", "--no-hashes", "--no-emit-project", "--no-header", "--no-dev"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    wanted = wanted_packages()
    lines = [line for line in exported.splitlines() if (m := re.match(r"^([A-Za-z0-9_.-]+)==", line)) and m.group(1).lower() in wanted]
    found = {re.match(r"^([A-Za-z0-9_.-]+)==", line).group(1).lower() for line in lines}
    if found != wanted:
        raise RuntimeError(f"uv export is missing {sorted(wanted - found)}")
    header = [
        "# Generated by scripts/export_kaggle_requirements.py from uv.lock; do not edit.",
        "# Kaggle keeps its preinstalled torch (decision 23); install jevmark itself with --no-deps.",
    ]
    return "\n".join(header + sorted(lines, key=str.lower)) + "\n"


def main() -> int:
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
